language: node_js
node_js:
  - lts/*
# node 19 is broken
# see https://travis-ci.community/t/the-command-npm-config-set-spin-false-failed-and-exited-with-1-during/12909/8
#  - node
os: linux
dist: focal
arch: arm64
cache:
  directories:
    - $HOME/.yarn/berry/cache
